### ISSUE TITLE
lex_error on Puppet's each function

### ISSUE THREAD

**Issue by RyPeck** [rodjek/rspec-puppet#171]
Attempting to run `rspec-puppet-init` on my module for the first time and it erred out when it countered a line in one of my manifests using the [each function](http://docs.puppetlabs.com/references/3.4.stable/function.html#each).

Example code that caused the error. Without using this function, rspec-puppet-init successfully runs.

```
$useable_ints = ['1', '2']
$useable_ints.each { |$int|
  notify("hey")
}
```

Does `rspec-puppet` not support functions that require `parser = future` be set in the `puppet.conf`?

Traceback - 
```
rypeck$ rspec-puppet-init 
/Library/Ruby/Gems/2.0.0/gems/puppet-3.4.2/lib/puppet/parser/lexer.rb:33:in `lex_error': Could not match |$int| (Puppet::LexError)
	from /Library/Ruby/Gems/2.0.0/gems/puppet-3.4.2/lib/puppet/parser/lexer.rb:466:in `scan'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-3.4.2/lib/puppet/parser/lexer.rb:339:in `fullscan'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/setup.rb:58:in `get_module_name_from_file'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/setup.rb:48:in `block in get_module_name'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/setup.rb:47:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/setup.rb:47:in `get_module_name'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/setup.rb:13:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-puppet-1.0.1/bin/rspec-puppet-init:20:in `<top (required)>'
	from /usr/bin/rspec-puppet-init:23:in `load'
	from /usr/bin/rspec-puppet-init:23:in `<main>'
```

**Comment by DavidS** [comment]
The real fix was released with 2.2 (https://github.com/rodjek/rspec-puppet/commit/e7f69fd267fff163fdf42c581096326284505e14). You still need to have a puppet version installed that can handle the code you're trying to parse.
