### ISSUE TITLE
Issue with Hiera in tests

### ISSUE THREAD

**Issue by aknapp** [rodjek/rspec-puppet#172]
Here's my Gemfile:

``` ruby
source 'https://rubygems.org/'

gem 'puppet', '3.4.2'
gem 'facter', '1.7.5'
gem 'rspec-puppet', :git => 'https://github.com/rodjek/rspec-puppet.git', :ref => '03e94422fb9bbdd950d5a0bec6ead5d76e06616b'
gem 'rake', '0.9.2.2'
gem 'puppet-lint', '0.3.2'
gem 'hiera', '1.3.1'
gem 'puppetlabs_spec_helper', '0.4.1'
```

I think I have hiera setup correctly, but whenever I try to lookup a value I get this:

``` ruby
DEBUG: 2014-02-16 16:23:16 -0800: Hiera JSON backend starting
DEBUG: 2014-02-16 16:23:16 -0800: Looking up nfs::master in JSON backend
/code/puppet/vendor/gems/ruby/2.0.0/gems/hiera-1.3.1/lib/hiera/interpolate.rb:34:in `scope_interpolate': undefined method `[]' for nil:NilClass (NoMethodError)
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/hiera-1.3.1/lib/hiera/interpolate.rb:13:in `block in interpolate'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/hiera-1.3.1/lib/hiera/recursive_guard.rb:16:in `check'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/hiera-1.3.1/lib/hiera/interpolate.rb:11:in `interpolate'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/hiera-1.3.1/lib/hiera/backend.rb:93:in `parse_string'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/hiera-1.3.1/lib/hiera/backend.rb:72:in `block in datasources'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/hiera-1.3.1/lib/hiera/backend.rb:71:in `map'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/hiera-1.3.1/lib/hiera/backend.rb:71:in `datasources'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/hiera-1.3.1/lib/hiera/backend/json_backend.rb:17:in `lookup'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/hiera-1.3.1/lib/hiera/backend.rb:174:in `block in lookup'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/hiera-1.3.1/lib/hiera/backend.rb:171:in `each'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/hiera-1.3.1/lib/hiera/backend.rb:171:in `lookup'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/hiera-1.3.1/lib/hiera.rb:60:in `lookup'
    from /code/puppet/modules/nfs/spec/classes/nfs_hiera_spec.rb:8:in `block in <top (required)>'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:246:in `module_eval'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:246:in `subclass'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:232:in `describe'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/dsl.rb:18:in `describe'
    from /code/puppet/modules/nfs/spec/classes/nfs_hiera_spec.rb:3:in `<top (required)>'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `load'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `block in load_spec_files' 
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `each'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `load_spec_files'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:22:in `run'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:80:in `run'
    from /code/puppet/vendor/gems/ruby/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:17:in `block in autorun'
```

My spec_helper is:

``` ruby
require 'hiera'
require 'rspec-puppet'

RSpec.configure do |c|
  c.hiera_config = 'spec/fixtures/hiera/hiera.yaml'
  c.manifest_dir = 'spec/fixtures/manifests'
  c.module_path = 'modules'
end

#at_exit { RSpec::Puppet::Coverage.report! }
```

The simple test I'm trying to run is:

``` ruby
require 'spec_helper'

describe 'nfs' do
  let (:title) { 'nfs' }

  hiera = Hiera.new(:config => 'spec/fixtures/hiera/hiera.yaml')

  nfs_master = hiera.lookup('nfs::master', nil, nil)
```

It fails right at that point. I know my hiera data is correct because I can manually query it through the CLI. Any ideas? From the looks of it I think I configured everything correctly.

**Comment by xalimar** [comment]
Thanks @iljaweis 

I also found that hiera.lookup('foo::bar', nil, :facts) worked in my case since I already populate facts using let(:facts) syntax.
