### ISSUE TITLE
1.0.1 fails with Puppet v3.7.4

### ISSUE THREAD

**Issue by rb2k** [rodjek/rspec-puppet#255]
Just tried upgrading and noticed that our specs broke, thought I'd file an issue for visibility:
```
Failure/Error: is_expected.to contain_package('mysql-client').with(
     NoMethodError:
       undefined method `setdefaults' for #<Puppet::Settings:0x00000000911bf8>
     # /home/travis/build/[...]/vendor/bundle/ruby/2.1.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/support.rb:120:in `rescue in block in setup_puppet'
     # /home/travis/build/[...]/vendor/bundle/ruby/2.1.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/support.rb:117:in `block in setup_puppet'
     # /home/travis/build/[...]/vendor/bundle/ruby/2.1.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/support.rb:115:in `each'
     # /home/travis/build/[...]/vendor/bundle/ruby/2.1.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/support.rb:115:in `setup_puppet'
     # /home/travis/build/[...]/vendor/bundle/ruby/2.1.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/support.rb:7:in `catalogue'
     # /home/travis/build/[...]/vendor/bundle/ruby/2.1.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/example/class_example_group.rb:7:in `subject'
     # ./spec/classes/client_spec.rb:19:in `block (2 levels) in <top (required)>'
```

**Comment by rb2k** [comment]
I think this might be related to https://github.com/rodjek/rspec-puppet/issues/263

**Comment by DavidS** [comment]
This should be fixed in 2.x
