### ISSUE TITLE
undefined method 'merge'

### ISSUE THREAD

**Issue by developerinlondon** [rodjek/rspec-puppet#278]
I am using the hiera config example from https://github.com/rodjek/rspec-puppet#configuration

but getting:
```
     Failure/Error: it { is_expected.to_not raise_error() }
       expected no Exception, got #<Puppet::Error: undefined method `merge' for "spec/fixtures/hiera/hiera.yaml":String at /Users/nayeem.syed/Documents/bgch/puppet-installer/modules/bgch_iscsi/spec/fixtures/modules/bgch_iscsi/manifests/config.pp:8 on node c324091.local> with backtrace:
         # /Users/nayeem.syed/.rvm/gems/ruby-2.1.2/gems/hiera-puppet-helper-1.0.1/lib/hiera-puppet-helper/puppet.rb:41:in `block in register_function_hiera'
         # /Users/nayeem.syed/.rvm/gems/ruby-2.1.2/gems/puppet-3.7.5/lib/puppet/parser/functions.rb:164:in `block (2 levels) in newfunction'
```

any ideas how i can fix this?

**Comment by DavidS** [comment]
hiera-puppet-helper overrides/replaces the functionality that is explained in the README section you're pointing to. Please remove that from your bundle and try again!
