### ISSUE TITLE
"No title provided and "foo" is not a valid resource reference" Failures with Puppet 4.5 

### ISSUE THREAD

**Issue by petems** [rodjek/rspec-puppet#390]
With Puppet 4.5, I'm getting the following failures:

```
 No title provided and "cockpit::config" is not a valid resource reference
```

Works fine with 4.4

Spec in question:

```ruby
require 'spec_helper'

describe 'cockpit' do

  shared_examples 'no parameters' do
    let(:params) {{ }}

    it { should compile.with_all_deps }

    it { should create_class('cockpit') }

    it { should contain_class('cockpit::params') }
    it { should contain_class('cockpit::repo').that_comes_before('cockpit::install') }
    it { should contain_class('cockpit::install').that_comes_before('cockpit::config') }
    it { should contain_class('cockpit::config') }
    it { should contain_class('cockpit::service').that_subscribes_to('cockpit::config') }

    it { should contain_ini_setting('Cockpit LoginTitle').with(
      :ensure    => 'present',
      :path      => '/etc/cockpit/cockpit.conf',
      :section   => 'WebService',
      :setting   => 'LoginTitle',
      :value     => facts[:fqdn],
      :show_diff => true,
      ) }

    it { should contain_ini_setting('Cockpit LoginTitle').with(
      :ensure    => 'present',
      :path      => '/etc/cockpit/cockpit.conf',
      :section   => 'WebService',
      :setting   => 'LoginTitle',
      :value     => facts[:fqdn],
      :show_diff => true,
      ) }

    it { should contain_ini_setting('Cockpit MaxStartups').with(
      :ensure    => 'present',
      :path      => '/etc/cockpit/cockpit.conf',
      :section   => 'WebService',
      :setting   => 'MaxStartups',
      :value     => '10',
      :show_diff => true,
      ) }

    it { should contain_ini_setting('Cockpit AllowUnencrypted').with(
      :ensure    => 'present',
      :path      => '/etc/cockpit/cockpit.conf',
      :section   => 'WebService',
      :setting   => 'AllowUnencrypted',
      :value     => false,
      :show_diff => true,
      ) }

    it { should contain_service('cockpit').with(
      :ensure => 'running',
      # :enable => 'true'
      )}
    it { should contain_package('cockpit').with_ensure('installed') }

    context 'with custom parameters' do
      context 'package name' do
        let(:params) {{ 'package_name' => 'custom-package' }}
        it { should contain_package("#{params['package_name']}") }
      end
      context 'package version' do
        let(:params) {{ 'package_version' => 'latest' }}
        it { should contain_package('cockpit').with_ensure('latest') }
      end
      context 'service name' do
        let(:params) {{ 'service_name' => 'custom-service' }}
        it { should contain_service("#{params['service_name']}") }
      end
      context 'port' do
        let(:params) {{ 'port' => '7777' }}
        it {
          should contain_file('/etc/systemd/system/cockpit.socket.d/listen.conf').
            with(:ensure    => 'file')
          should contain_file('/etc/systemd/system/cockpit.socket.d/listen.conf').
            with_content(/ListenStream=7777/)
          should contain_file('/etc/systemd/system/cockpit.socket.d/').
            with(:ensure    => 'directory')
          should contain_exec('Cockpit systemctl daemon-reload').with(
            :command     => 'systemctl daemon-reload',
            :refreshonly => true,
            :path => facts[:path],
          )
        }
      end
    end
  end

  on_supported_os.each do |os, facts|
    context "on #{os}" do
      let(:facts) do
        facts.merge({
          :fqdn => 'cockpit.example.com',
          :path => '/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin:/root/bin'
        })
      end

      it_behaves_like 'no parameters'
    end
  end

end
```

**Comment by DavidS** [comment]
Please point out which line this error is coming from.

**Comment by petems** [comment]
```
Failures:

  1) cockpit on centos-7-x86_64 behaves like no parameters should contain Class[cockpit::repo] that comes before cockpit::install
     Failure/Error: it { should contain_class('cockpit::repo').that_comes_before('cockpit::install') }

     ArgumentError:
       No title provided and "cockpit::install" is not a valid resource reference
     Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
     # ./spec/classes/cockpit_spec.rb:13:in `block (3 levels) in <top (required)>'

  2) cockpit on centos-7-x86_64 behaves like no parameters should contain Class[cockpit::install] that comes before cockpit::config
     Failure/Error: it { should contain_class('cockpit::install').that_comes_before('cockpit::config') }

     ArgumentError:
       No title provided and "cockpit::config" is not a valid resource reference
     Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
     # ./spec/classes/cockpit_spec.rb:14:in `block (3 levels) in <top (required)>'

  3) cockpit on centos-7-x86_64 behaves like no parameters should contain Class[cockpit::service] that subscribes to cockpit::config
     Failure/Error: it { should contain_class('cockpit::service').that_subscribes_to('cockpit::config') }

     ArgumentError:
       No title provided and "cockpit::config" is not a valid resource reference
     Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
     # ./spec/classes/cockpit_spec.rb:16:in `block (3 levels) in <top (required)>'

  4) cockpit on debian-8-x86_64 behaves like no parameters should contain Class[cockpit::repo] that comes before cockpit::install
     Failure/Error: it { should contain_class('cockpit::repo').that_comes_before('cockpit::install') }

     ArgumentError:
       No title provided and "cockpit::install" is not a valid resource reference
     Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
     # ./spec/classes/cockpit_spec.rb:13:in `block (3 levels) in <top (required)>'

  5) cockpit on debian-8-x86_64 behaves like no parameters should contain Class[cockpit::install] that comes before cockpit::config
     Failure/Error: it { should contain_class('cockpit::install').that_comes_before('cockpit::config') }

     ArgumentError:
       No title provided and "cockpit::config" is not a valid resource reference
     Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
     # ./spec/classes/cockpit_spec.rb:14:in `block (3 levels) in <top (required)>'

  6) cockpit on debian-8-x86_64 behaves like no parameters should contain Class[cockpit::service] that subscribes to cockpit::config
     Failure/Error: it { should contain_class('cockpit::service').that_subscribes_to('cockpit::config') }

     ArgumentError:
       No title provided and "cockpit::config" is not a valid resource reference
     Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
     # ./spec/classes/cockpit_spec.rb:16:in `block (3 levels) in <top (required)>'

  7) cockpit on fedora-22-x86_64 behaves like no parameters should contain Class[cockpit::repo] that comes before cockpit::install
     Failure/Error: it { should contain_class('cockpit::repo').that_comes_before('cockpit::install') }

     ArgumentError:
       No title provided and "cockpit::install" is not a valid resource reference
     Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
     # ./spec/classes/cockpit_spec.rb:13:in `block (3 levels) in <top (required)>'

  8) cockpit on fedora-22-x86_64 behaves like no parameters should contain Class[cockpit::install] that comes before cockpit::config
     Failure/Error: it { should contain_class('cockpit::install').that_comes_before('cockpit::config') }

     ArgumentError:
       No title provided and "cockpit::config" is not a valid resource reference
     Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
     # ./spec/classes/cockpit_spec.rb:14:in `block (3 levels) in <top (required)>'

  9) cockpit on fedora-22-x86_64 behaves like no parameters should contain Class[cockpit::service] that subscribes to cockpit::config
     Failure/Error: it { should contain_class('cockpit::service').that_subscribes_to('cockpit::config') }

     ArgumentError:
       No title provided and "cockpit::config" is not a valid resource reference
     Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
     # ./spec/classes/cockpit_spec.rb:16:in `block (3 levels) in <top (required)>'

  10) cockpit on redhat-7-x86_64 behaves like no parameters should contain Class[cockpit::repo] that comes before cockpit::install
      Failure/Error: it { should contain_class('cockpit::repo').that_comes_before('cockpit::install') }

      ArgumentError:
        No title provided and "cockpit::install" is not a valid resource reference
      Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
      # ./spec/classes/cockpit_spec.rb:13:in `block (3 levels) in <top (required)>'

  11) cockpit on redhat-7-x86_64 behaves like no parameters should contain Class[cockpit::install] that comes before cockpit::config
      Failure/Error: it { should contain_class('cockpit::install').that_comes_before('cockpit::config') }

      ArgumentError:
        No title provided and "cockpit::config" is not a valid resource reference
      Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
      # ./spec/classes/cockpit_spec.rb:14:in `block (3 levels) in <top (required)>'

  12) cockpit on redhat-7-x86_64 behaves like no parameters should contain Class[cockpit::service] that subscribes to cockpit::config
      Failure/Error: it { should contain_class('cockpit::service').that_subscribes_to('cockpit::config') }

      ArgumentError:
        No title provided and "cockpit::config" is not a valid resource reference
      Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
      # ./spec/classes/cockpit_spec.rb:16:in `block (3 levels) in <top (required)>'

  13) cockpit on ubuntu-16.04-x86_64 behaves like no parameters should contain Class[cockpit::repo] that comes before cockpit::install
      Failure/Error: it { should contain_class('cockpit::repo').that_comes_before('cockpit::install') }

      ArgumentError:
        No title provided and "cockpit::install" is not a valid resource reference
      Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
      # ./spec/classes/cockpit_spec.rb:13:in `block (3 levels) in <top (required)>'

  14) cockpit on ubuntu-16.04-x86_64 behaves like no parameters should contain Class[cockpit::install] that comes before cockpit::config
      Failure/Error: it { should contain_class('cockpit::install').that_comes_before('cockpit::config') }

      ArgumentError:
        No title provided and "cockpit::config" is not a valid resource reference
      Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
      # ./spec/classes/cockpit_spec.rb:14:in `block (3 levels) in <top (required)>'

  15) cockpit on ubuntu-16.04-x86_64 behaves like no parameters should contain Class[cockpit::service] that subscribes to cockpit::config
      Failure/Error: it { should contain_class('cockpit::service').that_subscribes_to('cockpit::config') }

      ArgumentError:
        No title provided and "cockpit::config" is not a valid resource reference
      Shared Example Group: "no parameters" called from ./spec/classes/cockpit_spec.rb:101
      # ./spec/classes/cockpit_spec.rb:16:in `block (3 levels) in <top (required)>'

Finished in 7.56 seconds (files took 1.62 seconds to load)
102 examples, 15 failures

Failed examples:

rspec ./spec/classes/cockpit_spec.rb[1:1:1:4] # cockpit on centos-7-x86_64 behaves like no parameters should contain Class[cockpit::repo] that comes before cockpit::install
rspec ./spec/classes/cockpit_spec.rb[1:1:1:5] # cockpit on centos-7-x86_64 behaves like no parameters should contain Class[cockpit::install] that comes before cockpit::config
rspec ./spec/classes/cockpit_spec.rb[1:1:1:7] # cockpit on centos-7-x86_64 behaves like no parameters should contain Class[cockpit::service] that subscribes to cockpit::config
rspec ./spec/classes/cockpit_spec.rb[1:2:1:4] # cockpit on debian-8-x86_64 behaves like no parameters should contain Class[cockpit::repo] that comes before cockpit::install
rspec ./spec/classes/cockpit_spec.rb[1:2:1:5] # cockpit on debian-8-x86_64 behaves like no parameters should contain Class[cockpit::install] that comes before cockpit::config
rspec ./spec/classes/cockpit_spec.rb[1:2:1:7] # cockpit on debian-8-x86_64 behaves like no parameters should contain Class[cockpit::service] that subscribes to cockpit::config
rspec ./spec/classes/cockpit_spec.rb[1:3:1:4] # cockpit on fedora-22-x86_64 behaves like no parameters should contain Class[cockpit::repo] that comes before cockpit::install
rspec ./spec/classes/cockpit_spec.rb[1:3:1:5] # cockpit on fedora-22-x86_64 behaves like no parameters should contain Class[cockpit::install] that comes before cockpit::config
rspec ./spec/classes/cockpit_spec.rb[1:3:1:7] # cockpit on fedora-22-x86_64 behaves like no parameters should contain Class[cockpit::service] that subscribes to cockpit::config
rspec ./spec/classes/cockpit_spec.rb[1:4:1:4] # cockpit on redhat-7-x86_64 behaves like no parameters should contain Class[cockpit::repo] that comes before cockpit::install
rspec ./spec/classes/cockpit_spec.rb[1:4:1:5] # cockpit on redhat-7-x86_64 behaves like no parameters should contain Class[cockpit::install] that comes before cockpit::config
rspec ./spec/classes/cockpit_spec.rb[1:4:1:7] # cockpit on redhat-7-x86_64 behaves like no parameters should contain Class[cockpit::service] that subscribes to cockpit::config
rspec ./spec/classes/cockpit_spec.rb[1:5:1:4] # cockpit on ubuntu-16.04-x86_64 behaves like no parameters should contain Class[cockpit::repo] that comes before cockpit::install
rspec ./spec/classes/cockpit_spec.rb[1:5:1:5] # cockpit on ubuntu-16.04-x86_64 behaves like no parameters should contain Class[cockpit::install] that comes before cockpit::config
rspec ./spec/classes/cockpit_spec.rb[1:5:1:7] # cockpit on ubuntu-16.04-x86_64 behaves like no parameters should contain Class[cockpit::service] that subscribes to cockpit::config
```

**Comment by DavidS** [comment]
that_comes_before() takes a resource reference as argument. It should say `.that_comes_before('Class[cockpit::install]')`

No idea how that worked before.

**Comment by petems** [comment]
Ok, I should probably go update the Puppet skeleton cos it's fron that! 😱

**Comment by DavidS** [comment]
:100: x :+1:

**Comment by DavidS** [comment]
Please close this once you have confirmed the fix.

**Comment by petems** [comment]
https://github.com/petems/petems-cockpit/pull/13 is green! Closing
