### ISSUE TITLE
Manifest directory detected at the wrong path

### ISSUE THREAD

**Issue by ranzbak** [rodjek/rspec-puppet#392]
vagrant@debian-jessie:/vagrant/modules/brive$ bundle exec rspec-puppet-init
/usr/lib/ruby/2.1.0/fileutils.rb:355:in `symlink': Protocol error @ sys_fail2 - (../../../../manifests, spec/fixtures/modules/brive/manifests) (Errno::EPROTO)
	from /usr/lib/ruby/2.1.0/fileutils.rb:355:in `block in ln_s'
	from /usr/lib/ruby/2.1.0/fileutils.rb:1595:in `fu_each_src_dest0'
	from /usr/lib/ruby/2.1.0/fileutils.rb:353:in `ln_s'
	from /var/lib/gems/2.1.0/gems/rspec-puppet-2.4.0/lib/rspec-puppet/setup.rb:128:in `safe_make_symlink'
	from /var/lib/gems/2.1.0/gems/rspec-puppet-2.4.0/lib/rspec-puppet/setup.rb:39:in `block in run'
	from /var/lib/gems/2.1.0/gems/rspec-puppet-2.4.0/lib/rspec-puppet/setup.rb:37:in `each'
	from /var/lib/gems/2.1.0/gems/rspec-puppet-2.4.0/lib/rspec-puppet/setup.rb:37:in `run'
	from /var/lib/gems/2.1.0/gems/rspec-puppet-2.4.0/bin/rspec-puppet-init:20:in `<top (required)>'
	from /usr/local/bin/rspec-puppet-init:23:in `load'
	from /usr/local/bin/rspec-puppet-init:23:in `<main>'

I can't get rspec-puppet-init to setup the test fixtures correctly.

**Comment by ranzbak** [comment]
I found the problem, when I use the 'rspec-puppet-init' command on a path outside of my home, it fails.
In this case '/vagrant/modules/brive', but when I move the module to '/home/vagrant/brive' the script starts working. 
It seems the 'rspec-puppet-init' script breaks when used outside of the home dir.

**Comment by ranzbak** [comment]
I found the problem in that Vagrant doesn't support symlinks in the /vagrant shared filesystem.
