### ISSUE TITLE
Certain relationship checks cause "SystemStackError: stack level too deep"

### ISSUE THREAD

**Issue by tylerjl** [rodjek/rspec-puppet#418]
Although I've found similar problems come up for people with rspec in general, I've reproduced this specific case in `rspec-puppet` so I'm pretty sure this belongs here.

I've come across this issue in [puppet-elasticsearch](https://github.com/elastic/puppet-elasticsearch) for some certain checks. Although I don't have a simple reproducible case with a bare-bones `_spec.rb` file, I do have a reproducible case in the `puppet-elasticsearch` repo given the following steps:

``` shell
$ git clone git@github.com:elastic/puppet-elasticsearch.git
$ cd puppet-elasticsearch
$ git checkout 16559274
$ bundle install
$ bundle exec rake spec_prep
$ bundle exec rspec spec/defines/007_elasticsearch_shield_user_spec.rb
```

Note that per the nature of the issue, the output is prohibitively long, so here's the output trimmed for readability:

```
................F

Failures:

  1) elasticsearch::shield::user collector ordering when absent should contain Elasticsearch::Shield::User[elastic] that comes before Elasticsearch::Template[foo] and Elasticsearch::Plugin[shield]
     Failure/Error:
       it { should contain_elasticsearch__shield__user('elastic')
         .that_comes_before([
         'Elasticsearch::Template[foo]',
         'Elasticsearch::Plugin[shield]'
       ]).that_requires([
         'Elasticsearch::Shield::Role[test_role]'
       ])}

     SystemStackError:
       stack level too deep
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/puppet-3.8.7/lib/puppet/util/tagging.rb:19:in `block (2 levels) in tag'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/puppet-3.8.7/lib/puppet/util/tagging.rb:18:in `each'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/puppet-3.8.7/lib/puppet/util/tagging.rb:18:in `block in tag'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/puppet-3.8.7/lib/puppet/util/tagging.rb:13:in `each'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/puppet-3.8.7/lib/puppet/util/tagging.rb:13:in `tag'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/puppet-3.8.7/lib/puppet/resource.rb:247:in `initialize'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/puppet-3.8.7/lib/puppet/resource/catalog.rb:302:in `new'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/puppet-3.8.7/lib/puppet/resource/catalog.rb:302:in `resource'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:239:in `resource_from_ref'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:247:in `canonicalize_resource_ref'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:255:in `block in relationship_refs'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:254:in `each'

     ... endless alternating between relationship_refs and each ...

     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:254:in `relationship_refs'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:283:in `block (2 levels) in precedes?'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:282:in `each'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:282:in `block in precedes?'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:281:in `each'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:281:in `precedes?'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:204:in `block in check_befores'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:203:in `each'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:203:in `check_befores'
     # /Users/tylerjl/.rvm/gems/ruby-2.3.1/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:99:in `matches?'
     # ./spec/defines/007_elasticsearch_shield_user_spec.rb:110:in `block (4 levels) in <top (required)>'

Finished in 4.53 seconds (files took 0.81035 seconds to load)
17 examples, 1 failure

Failed examples:

rspec ./spec/defines/007_elasticsearch_shield_user_spec.rb:110 # elasticsearch::shield::user collector ordering when absent should contain Elasticsearch::Shield::User[elastic] that comes before Elasticsearch::Template[foo] and Elasticsearch::Plugin[shield]
```

This problem does **not** occur as of version v2.2.0, and I suspect the problem may be at least tangentially related to changes that modified how `relationship_ref` works.

For reference, the lines that cause this:

``` ruby
      it { should contain_elasticsearch__shield__user('elastic')
        .that_comes_before([
        'Elasticsearch::Template[foo]',
        'Elasticsearch::Plugin[shield]'
      ]).that_requires([
        'Elasticsearch::Shield::Role[test_role]'
      ])}
```

Changing that line to only singly test relationships (i.e., not chained), or checking only one relationship at a time, don't change the results.

**Comment by tylerjl** [comment]
Adding some additional information here; the breaking change on the puppet side is this:

```
$ git --no-pager diff 2e1b583...065d8ea manifests/init.pp
diff --git a/manifests/init.pp b/manifests/init.pp
index 0a435eb..e151bdb 100644
--- a/manifests/init.pp
+++ b/manifests/init.pp
@@ -669,7 +669,9 @@ class elasticsearch(

     # Top-level ordering bindings for resources.
     Class['elasticsearch::config']
-    -> Elasticsearch::Plugin <| |>
+    -> Elasticsearch::Plugin <| ensure == 'present' or ensure == 'installed' |>
+    Elasticsearch::Plugin <| ensure == 'absent' |>
+    -> Class['elasticsearch::config']
     Class['elasticsearch::config']
     -> Elasticsearch::Instance <| |>
     Class['elasticsearch::config']
```

Reverting that change causes the test to succeed. Note that the overall Puppet use case here works as intended when testing by hand in a clean environment; the ordering with conditionally collected resources looks fine from the end-user perspective.

It would seem that conditionally collected resources with relationships may cause infinite recursion in some cases, but I don't know the rspec-puppet codebase well enough to pinpoint where to start looking for a fix. Note that this behavior is exhibited in `v2.3.0` but **not** `v2.2.0`, so the breakage is somewhere in there.
