### ISSUE TITLE
Function testing with type aliases fails

### ISSUE THREAD

**Issue by seanmil** [rodjek/rspec-puppet#484]
When using a custom Puppet data type alias as a type on a parameter to a function AND, at the same time, using it as a parameter on a class in the module containing the function then spec tests on that function fail with an exception like the following:

```
       expected aliases::myfunc("circle") to have returned "circle" instead of raising Puppet::PreformattedError(Evaluation Error: Error while evaluating a Type-Name, Attempt to redefine entity 'http://puppet.com/2016.1/runtime/type/aliases::shape'. Originally set rspec-puppet/spec/fixtures/modules/aliases/types/shape.pp. at rspec-puppet/spec/fixtures/modules/aliases/functions/myfunc.pp:2:3)
```

You can see the spec tests I added which demonstrate this issue here: https://github.com/seanmil/rspec-puppet/tree/function_type_aliases

I have reviewed the code, but don't have a clear idea what the cause would be.

I found it interesting to note that if the reference to the data type alias is removed from the class (in `aliases/manifests/init.pp`) then the tests work just fine.

**Comment by DavidS** [comment]
Hmm, curious. Can you confirm that this is a rspec-puppet problem, and does not happen with running the same code in `puppet apply`?

**Comment by DavidS** [comment]
(also: which puppet version are you using?)

**Comment by seanmil** [comment]
It works fine with `puppet apply` on 4.7.0 on the module in the spec test I referenced above:
```
$ puppet apply --modulepath=rspec-puppet/spec/fixtures/modules -e 'class { "aliases": shape => "square" }'
Notice: Compiled catalog for msp-pumtl31.msp.secure-24.net in environment production in 0.24 seconds
Notice: square
Notice: /Stage[main]/Aliases/Notify[square]/message: defined 'message' as 'square'
Notice: Applied catalog in 0.04 seconds
```
When running the spec tests in the rspec-puppet framework I also saw this fail both with 4.7.0 and with a gem install of puppet 4.9.4.

**Comment by DavidS** [comment]
The full test failure from the linked branch. There are two more of the same. I'll take a WAG and say that the function's test group is doing something funky, and wrong, with setting up the loaders. @hlindberg , @thallgren can you have a look at this stacktrace?

```
david@davids:~/git/rspec-puppet$ bundle exec rspec ./spec/functions/type_aliases_spec.rb:5
Run options: include {:locations=>{"./spec/functions/type_aliases_spec.rb"=>[5]}}

aliases::myfunc
  should run aliases::myfunc("circle") and return "circle" (FAILED - 1)

Total resources:   0
Touched resources: 0
Resource coverage:   NaN%
Untouched resources:



Failures:

  1) aliases::myfunc should run aliases::myfunc("circle") and return "circle"
     Failure/Error: it { should run.with_params('circle').and_return('circle') }
     
       expected aliases::myfunc("circle") to have returned "circle" instead of raising Puppet::PreformattedError(Evaluation Error: Error while evaluating a Type-Name, Attempt to redefine entity 'http://puppet.com/2016.1/runtime/type/aliases::shape'. Originally set /home/david/git/rspec-puppet/spec/fixtures/modules/aliases/types/shape.pp. at /home/david/git/rspec-puppet/spec/fixtures/modules/aliases/functions/myfunc.pp:2:3)
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/loader/base_loader.rb:113:in `fail_redefine'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/loader/base_loader.rb:63:in `set_entry'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/loader/module_loaders.rb:158:in `find'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/loader/base_loader.rb:142:in `internal_load'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/loader/base_loader.rb:32:in `load_typed'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/loader/base_loader.rb:141:in `internal_load'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/loader/base_loader.rb:32:in `load_typed'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/loader/loader.rb:49:in `load'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/types/type_parser.rb:194:in `interpret_QualifiedReference'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/visitor.rb:69:in `visit_this_1'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/types/type_parser.rb:52:in `interpret'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/evaluator/evaluator_impl.rb:312:in `eval_QualifiedReference'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/visitor.rb:48:in `block in visit_this'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/visitor.rb:42:in `each'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/visitor.rb:42:in `visit_this'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/visitor.rb:71:in `visit_this_1'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/evaluator/evaluator_impl.rb:82:in `evaluate'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/evaluator/closure.rb:331:in `create_param_type'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/evaluator/closure.rb:290:in `block in create_callable_type'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/evaluator/closure.rb:289:in `each'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/evaluator/closure.rb:289:in `create_callable_type'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/evaluator/closure.rb:138:in `type'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/functions/dispatcher.rb:31:in `block in dispatch'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/functions/dispatcher.rb:31:in `each'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/functions/dispatcher.rb:31:in `find'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/functions/dispatcher.rb:31:in `dispatch'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/functions/function.rb:46:in `block in call'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/functions/function.rb:45:in `catch'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/pops/functions/function.rb:45:in `call'
       /home/david/git/rspec-puppet/lib/rspec-puppet/example/function_example_group.rb:19:in `block in execute'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet/context.rb:65:in `override'
       /home/david/gems/ruby/2.3.0/gems/puppet-4.9.4/lib/puppet.rb:293:in `override'
       /home/david/git/rspec-puppet/lib/rspec-puppet/example/function_example_group.rb:18:in `execute'
       /home/david/git/rspec-puppet/lib/rspec-puppet/matchers/run.rb:10:in `matches?'
       /home/david/gems/ruby/2.3.0/gems/rspec-expectations-3.5.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
       /home/david/gems/ruby/2.3.0/gems/rspec-expectations-3.5.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
       /home/david/gems/ruby/2.3.0/gems/rspec-expectations-3.5.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/memoized_helpers.rb:81:in `should'
       /home/david/git/rspec-puppet/spec/functions/type_aliases_spec.rb:5:in `block (2 levels) in <top (required)>'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:254:in `instance_exec'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:254:in `block in run'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:496:in `block in with_around_and_singleton_context_hooks'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:453:in `block in with_around_example_hooks'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:464:in `block in run'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:464:in `run'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:453:in `with_around_example_hooks'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:496:in `with_around_and_singleton_context_hooks'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:251:in `run'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:627:in `block in run_examples'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:623:in `map'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:623:in `run_examples'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:589:in `run'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `block (3 levels) in run_specs'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `map'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `block (2 levels) in run_specs'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1835:in `with_suite_hooks'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:112:in `block in run_specs'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:77:in `report'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:111:in `run_specs'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:87:in `run'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
       /home/david/gems/ruby/2.3.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
       /home/david/gems/ruby/2.3.0/bin/rspec:22:in `load'
       /home/david/gems/ruby/2.3.0/bin/rspec:22:in `<main>'
     # ./spec/functions/type_aliases_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 0.14008 seconds (files took 0.77363 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/functions/type_aliases_spec.rb:5 # aliases::myfunc should run aliases::myfunc("circle") and return "circle"

david@davids:~/git/rspec-puppet$ 
```

**Comment by thallgren** [comment]
@DavidS , thanks for making me aware of this. I looked into it and found it to be a bug in Puppet. I created [PUP-7391](https://tickets.puppetlabs.com/browse/PUP-7391) to track.

**Comment by DavidS** [comment]
@thallgren thanks for quick analysis!

@seanmil given the nature of the issue, a possible workaround might be to trigger a load of the type before hitting the actual test. Adding something to do so in the `pre_condition` might do that. If that works for you, at least you can move on while this gets fixed.

**Comment by seanmil** [comment]
Yes, adding an include for the class in the `pre_condition` was a usable workaround for me in this situation.
@DavidS @thallgren thanks to you both for your quick attention to this issue!
