### ISSUE TITLE
[question] Disable debugging stdout when using hiera

### ISSUE THREAD

**Issue by lmayorga1980** [rodjek/rspec-puppet#486]
Following configuration works for me but ...

```ruby
require 'puppetlabs_spec_helper/module_spec_helper'
require 'hiera' 

#https://github.com/rodjek/rspec-puppet

@hiera = Hiera.new(:config => 'spec/fixtures/hiera.yaml')

RSpec.configure do |c|
   c.hiera_config = 'spec/fixtures/hiera.yaml'
   c.after(:suite) do
      RSpec::Puppet::Coverage.report!
    end
end
```

Is there disable poisoning debugging messages configuration setting?

```shell
DEBUG: 2017-03-29 21:48:25 -0400: Hiera YAML backend starting
DEBUG: 2017-03-29 21:48:25 -0400: Looking up rmquser in YAML backend
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Looking up rmqversion in YAML backend
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Looking up rmqpassword in YAML backend
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Looking up erlang_package_version in YAML backend
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Looking up erlang_version in YAML backend
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Looking up erlang_cookie in YAML backend
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Looking up start_date in YAML backend
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Looking up start_time in YAML backend
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
DEBUG: 2017-03-29 21:48:25 -0400: Ignoring bad definition in :hierarchy: ''
```

**Comment by rodjek** [comment]
You should be able to disable Hiera's logging by adding `@hiera.logger = Hiera::Noop_logger` to your spec_helper

**Comment by rodjek** [comment]
Sorry, just checked the hiera code again and that line should be `@hiera.logger = 'noop'`

**Comment by lmayorga1980** [comment]
uhmmm...

```ruby
require 'puppetlabs_spec_helper/module_spec_helper'
require 'hiera' 

#https://github.com/rodjek/rspec-puppet

@hiera = Hiera.new(:config => 'spec/fixtures/hiera.yaml')
@hiera.logger = 'noop'

RSpec.configure do |c|
   c.hiera_config = 'spec/fixtures/hiera.yaml'
   c.after(:suite) do
      RSpec::Puppet::Coverage.report!
    end
end

```

```shell
/Users/git/puppet/puppet-rabbitmq/spec/spec_helper.rb:5:in `<top (required)>': undefined method `logger=' for nil:NilClass (NoMethodError)
	from /Users/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/git/puppet/puppet-rabbitmq/spec/classes/init_spec.rb:1:in `<top (required)>'
	from /Users/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /Users/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /Users/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /Users/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /Users.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /Users.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /Users/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /Users/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>'
```

**Comment by lmayorga1980** [comment]
worked!! thanks again 👍 

```yaml
---
:backends:
  - yaml
:yaml:
  :datadir: spec/fixtures/hieradata
:hierarchy:
  - "%{::clientcert}"
  - "%{::osfamily}"
:logger: noop
```

**Comment by rodjek** [comment]
Sorry, this is actually unrelated to the rspec-puppet code and I haven't gone through the Hiera code in a while, so bear with me :)

Just tried it out and logger is actually a method on the class, not the instance, so

```
Hiera.logger = 'noop'
@hiera = Hiera.new(path)
```

**Comment by rodjek** [comment]
Ah, cool, glad it's working for you :)
