### ISSUE TITLE
edge-case leading to spurious assert_no_example_groups_defined error

### ISSUE THREAD

**Issue by alexharv074** [rodjek/rspec-puppet#533]
I have a Puppet module that includes a defined type found in a second Puppet module, via `.fixtures.yml`. The defined type is then combined with template data that lives in the local module. I also use pure Rspec to do other testing in the local module, but this has nothing to do with Puppet.

My spec helper has (showing line numbers):

``` ruby
...
  4 require 'puppetlabs_spec_helper/module_spec_helper'
  5 
  6 RSpec.configure do |c|
  7   c.default_facts = {
  8     :ipaddress => '1.1.1.1',
  9   }
 10 end

```

If I run the tests I see: `assert_no_example_groups_defined': RSpec's mock_framework configuration option must be configured before any example groups are defined, but you have already defined a group.`

Full trace:

```
/Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.0/lib/rspec/core/configuration.rb:1976:in `assert_no_example_groups_defined': RSpec's mock_framework configuration option must be configured before any example groups are defined, but you have already defined a group. (RSpec::Core::Configuration::MustBeConfiguredBeforeExampleGroupsError)
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.0/lib/rspec/core/configuration.rb:670:in `mock_with'
        from /Library/Ruby/Gems/2.0.0/gems/puppetlabs_spec_helper-1.1.1/lib/puppetlabs_spec_helper/puppet_spec_helper.rb:122:in `block in <top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.0/lib/rspec/core.rb:97:in `configure'
        from /Library/Ruby/Gems/2.0.0/gems/puppetlabs_spec_helper-1.1.1/lib/puppetlabs_spec_helper/puppet_spec_helper.rb:120:in `<top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/puppetlabs_spec_helper-1.1.1/lib/puppetlabs_spec_helper/module_spec_helper.rb:2:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/puppetlabs_spec_helper-1.1.1/lib/puppetlabs_spec_helper/module_spec_helper.rb:2:in `<top (required)>'
        from /Users/alexharvey/git/amp/CAP/amp-puppet-jenkins_config/spec/spec_helper.rb:4:in `require'
        from /Users/alexharvey/git/amp/CAP/amp-puppet-jenkins_config/spec/spec_helper.rb:4:in `<top (required)>'
        from /Users/alexharvey/git/amp/CAP/amp-puppet-jenkins_config/spec/defines/jobs/characters_spec.rb:4:in `require'
        from /Users/alexharvey/git/amp/CAP/amp-puppet-jenkins_config/spec/defines/jobs/characters_spec.rb:4:in `<top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.0/lib/rspec/core/configuration.rb:1435:in `load'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.0/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.0/lib/rspec/core/configuration.rb:1433:in `each'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.0/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.0/lib/rspec/core/runner.rb:100:in `setup'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.0/lib/rspec/core/runner.rb:86:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.0/lib/rspec/core/runner.rb:71:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.0/lib/rspec/core/runner.rb:45:in `invoke'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.0/exe/rspec:4:in `<main>'
```

Workaround:

I create a file `spec/classes/init_spec.rb` that contains an empty describe block.

``` ruby
require 'spec_helper'
describe 'foo' do
end
```

'foo' here can really be any string at all.

I assume this is a bug?

**Comment by rodjek** [comment]
puppetlabs_spec_helper configures RSpec to use the mocha framework automatically. From the error, it looks like your ruby spec are getting loaded before the spec helper (in the 3 lines above where you're requiring `puppetlabs_spec_helper` perhaps).

This seems very specific to your setup, so it'd help me a lot if you could create a sample repo that recreates the problem and send me a link to it.

**Comment by alexharv074** [comment]
@rodjek No problem, I do as you say.

**Comment by alexharv074** [comment]
To be honest, I am struggling to reproduce this outside of my actual repos. If you're really interested I can email you a tarball, but probably best just to let me figure out the root cause in due course and leave this issue here open in case someone else needs to know the work-around.

**Comment by alexharv074** [comment]
Feel free to close this issue if you prefer.

**Comment by rodjek** [comment]
@alexharv074 If you're ok with emailing me a tarball, I'm happy to take a look :)

I will close out this issue for now though to keep the issue list clean, we can always reopen it if a reproducible bug is found.

**Comment by alexharv074** [comment]
@rodjek 

I figured out how to reproduce it.

Create a puppet class in manifests/init.pp:

``` puppet
class foo {
  notify { 'I, Foo': }
}
```

Create an Rspec puppet test in spec/classes/init.pp

``` ruby
require 'spec_helper'

describe 'foo', :type => :class do
  it { File.write('myclass.json', PSON.pretty_generate(catalogue)) }
end
```

Create a spec_helper:

``` ruby
require 'puppetlabs_spec_helper/module_spec_helper'
```

Compile - all is good.

Now add a describe block in another file using pure Rspec. Give this file a filename such that it sorts ahead of the other file and therefore will be loaded first:

``` ruby
describe 'readme' do
  it 'should have a readme' do
    expect { File.open('README.md') }.to_not raise_error
  end
end
```

Now try to compile:

```
$ bundle exec rake spec
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I/Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/lib:/Library/Ruby/Gems/2.0.0/gems/rspec-support-3.5.0/lib /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/exe/rspec --pattern spec/\{aliases,classes,defines,unit,functions,hosts,integration,types\}/\*\*/\*_spec.rb --color
/Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1982:in `assert_no_example_groups_defined': RSpec's mock_framework configuration option must be configured before any example groups are defined, but you have already defined a group. (RSpec::Core::Configuration::MustBeConfiguredBeforeExampleGroupsError)
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:670:in `mock_with'
        from /Library/Ruby/Gems/2.0.0/gems/puppetlabs_spec_helper-1.2.2/lib/puppetlabs_spec_helper/puppet_spec_helper.rb:122:in `block in <top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/lib/rspec/core.rb:97:in `configure'
        from /Library/Ruby/Gems/2.0.0/gems/puppetlabs_spec_helper-1.2.2/lib/puppetlabs_spec_helper/puppet_spec_helper.rb:120:in `<top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/puppetlabs_spec_helper-1.2.2/lib/puppetlabs_spec_helper/module_spec_helper.rb:2:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/puppetlabs_spec_helper-1.2.2/lib/puppetlabs_spec_helper/module_spec_helper.rb:2:in `<top (required)>'
        from /Users/alexharvey/git/modules/foo/spec/spec_helper.rb:1:in `require'
        from /Users/alexharvey/git/modules/foo/spec/spec_helper.rb:1:in `<top (required)>'
        from /Users/alexharvey/git/modules/foo/spec/classes/test_spec.rb:1:in `require'
        from /Users/alexharvey/git/modules/foo/spec/classes/test_spec.rb:1:in `<top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1435:in `load'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1433:in `each'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:100:in `setup'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:86:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:71:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:45:in `invoke'
        from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/exe/rspec:4:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I/Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/lib:/Library/Ruby/Gems/2.0.0/gems/rspec-support-3.5.0/lib /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.5.3/exe/rspec --pattern spec/\{aliases,classes,defines,unit,functions,hosts,integration,types\}/\*\*/\*_spec.rb --color failed
```

Workaround:

Add a line `require 'spec_helper'` at the top of the file that is being loaded ahead of the Rspec-puppet tests.

**Comment by alexharv074** [comment]
There is a minimal module available to reproduce the issue here
https://github.com/alexharv074/puppet-test/tree/53b409235e0b2a310780d698b929081e9ca4474a

Use that tree, because I'll probably write over that soon.

**Comment by rodjek** [comment]
Yeah, this is an unfortunate problem with using puppetlabs_spec_helper (related, but not part of this project) as it automatically configures RSpec to use Mocha as the mocking framework. So basically, if you use puppetlabs_spec_helper, you have to ensure that you always require 'spec_helper' at the start of all your spec files to ensure that no examples are added to RSpec's world before puppetlabs_spec_helper configures RSpec.
