### ISSUE TITLE
2.6.5 caused coverage issue

### ISSUE THREAD

**Issue by cdenneen** [rodjek/rspec-puppet#586]
Undefined method environment and clear

**2.6.4**
```
I, [2017-08-04T18:35:03.085270 #64300]  INFO -- : Creating symlink from spec/fixtures/modules/profile_base to /Users/cdenneen/temp/puppet-profile_base
/opt/rubies/2.1.8/bin/ruby -I/Users/cdenneen/temp/puppet-profile_base/.bundle/gems/rspec-core-3.6.0/lib:/Users/cdenneen/temp/puppet-profile_base/.bundle/gems/rspec-support-3.6.0/lib /Users/cdenneen/temp/puppet-profile_base/.bundle/gems/rspec-core-3.6.0/exe/rspec --pattern spec/\{aliases,classes,defines,unit,functions,hosts,integration,type_aliases,types\}/\*\*/\*_spec.rb --color
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Total resources:   88
Touched resources: 87
Resource coverage: 98.86%
Untouched resources:

  Stage[last]


Finished in 42.03 seconds (files took 8.47 seconds to load)
622 examples, 0 failures
```

**2.6.5**
```
I, [2017-08-04T18:38:02.637761 #67770]  INFO -- : Creating symlink from spec/fixtures/modules/profile_base to /Users/cdenneen/temp/puppet-profile_base
/opt/rubies/2.1.8/bin/ruby -I/Users/cdenneen/temp/puppet-profile_base/.bundle/gems/rspec-core-3.6.0/lib:/Users/cdenneen/temp/puppet-profile_base/.bundle/gems/rspec-support-3.6.0/lib /Users/cdenneen/temp/puppet-profile_base/.bundle/gems/rspec-core-3.6.0/exe/rspec --pattern spec/\{aliases,classes,defines,unit,functions,hosts,integration,type_aliases,types\}/\*\*/\*_spec.rb --color
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Total resources:   88
Touched resources: 87
Resource coverage: 98.86%
Untouched resources:

  Stage[last]
F

Failures:

  1) Code coverage. Must be at least 95% of code coverage
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: RSpec::Puppet::Coverage.report!(95)

          NoMethodError:
            undefined method `environment' for #<RSpec::ExampleGroups::CodeCoverage:0x007fa8a314a6d8>
          # ./.bundle/gems/rspec-puppet-2.6.5/lib/rspec-puppet/adapters.rb:67:in `setup_puppet'
          # ./.bundle/gems/rspec-puppet-2.6.5/lib/rspec-puppet/adapters.rb:111:in `setup_puppet'
          # ./.bundle/gems/rspec-puppet-2.6.5/lib/rspec-puppet.rb:99:in `block (2 levels) in <top (required)>'
          # ./.bundle/gems/rspec-puppet-2.6.5/lib/rspec-puppet/coverage.rb:106:in `coverage_test'
          # ./.bundle/gems/rspec-puppet-2.6.5/lib/rspec-puppet/coverage.rb:95:in `report!'
          # ./spec/spec_helper_local.rb:13:in `block (2 levels) in <top (required)>'

     1.2) Failure/Error: RSpec::Puppet::Coverage.report!(95)

          NoMethodError:
            undefined method `clear' for nil:NilClass
          # ./.bundle/gems/puppetlabs_spec_helper-2.3.1/lib/puppetlabs_spec_helper/puppet_spec_helper.rb:157:in `block (2 levels) in <top (required)>'
          # ./.bundle/gems/rspec-puppet-2.6.5/lib/rspec-puppet/coverage.rb:106:in `coverage_test'
          # ./.bundle/gems/rspec-puppet-2.6.5/lib/rspec-puppet/coverage.rb:95:in `report!'
          # ./spec/spec_helper_local.rb:13:in `block (2 levels) in <top (required)>'

Finished in 22.73 seconds (files took 8.49 seconds to load)
622 examples, 1 failure

Failed examples:

rspec  # Code coverage. Must be at least 95% of code coverage
```

**Comment by rodjek** [comment]
Hi @cdenneen,

Can you create a small sample repo that recreates the problem (or send me a link to the repo you're using above if it's public)?

**Comment by cdenneen** [comment]
@rodjek I found the issue... not sure why it showed up in 2.6.5 but not 2.6.4.
It happens when there is a missing test for a Stage in the rspec testing.
If the tests for specific resources including stages were missing in <= 2.6.4 this undefined method error didn't happen. If I add a test for it, it fixes the issue. While having all tests are good the fact if one is missing I'm not sure if the error should happen though.

If you look at this repo I've stripped it down to it's bare minimum test. Master branch is fixes with the test but the initial commit will show you the error so  you can reproduce locally:

https://github.com/cdenneen/rspec-puppet-test/tree/a0bc21666fc924974bbfa380711806f5184daa75

**Comment by rodjek** [comment]
Thanks for providing the reproducing example, I'll take a look and let you know!

**Comment by rodjek** [comment]
@cdenneen I've identified the issue and opened a PR to fix it for the next release (which will probably be sometime tomorrow)

**Comment by cdenneen** [comment]
@rodjek Thanks for the quick turn around
