### ISSUE TITLE
10x performance decrease in Rspec-puppet >2.6.4

### ISSUE THREAD

**Issue by fatmcgav** [rodjek/rspec-puppet#595]
I've been investigating a massive slow down in our CI builds, in the region of a 10x increase in build times.

The only trigger I can see for the increase is an upgrade of rspec-puppet from 2.6.4 to 2.6.5 or newer. 

Running some tests locally on a fairly small module, I get the following:
```
# rspec-puppet 2.6.4
Finished in 10.95 seconds (files took 4.41 seconds to load)
44 examples, 0 failures

bundle exec rake test  12.38s user 5.03s system 57% cpu 30.184 total

# rspec-puppet 2.6.5
Finished in 1 minute 38.27 seconds (files took 3.57 seconds to load)
44 examples, 0 failures

bundle exec rake test  66.40s user 11.26s system 69% cpu 1:52.50 total

# rspec-puppet 2.6.6
Finished in 1 minute 58.54 seconds (files took 3.88 seconds to load)
44 examples, 0 failures

bundle exec rake test  70.44s user 11.85s system 61% cpu 2:13.22 total

# rspec-puppet 2.6.7
Finished in 1 minute 18.75 seconds (files took 3.41 seconds to load)
44 examples, 0 failures

bundle exec rake test  63.44s user 9.35s system 81% cpu 1:28.88 total
```

As you can see, there's about a 10x increase in run-time between 2.6.4 and 2.6.5. 

Any ideas?

**Comment by rodjek** [comment]
Hi @fatmcgav,

Is this for an open source module by any chance? I'd love to get some ruby-prof results to see where the slowdown occurs

**Comment by fatmcgav** [comment]
@rodjek So far these are all private repos'... 
However I've got a couple of open-source ones I can try it on... 

Alternatively if ruby-prof is easy enough to run I can do that too...

**Comment by rodjek** [comment]
@fatmcgav If you could gather the results and email them through to me, that would be awesome. You can install ruby-prof as a gem by adding it to your Gemfile and then doing something like `bundle exec ruby-prof rspec`

**Comment by fatmcgav** [comment]
@rodjek Sure, I'll give that a go :)

**Comment by fatmcgav** [comment]
@rodjek Whilst I gather the stats on our private repos, I've just been able to reproduce the same behaviour on https://github.com/fatmcgav/fatmcgav-glassfish.

- Rspec-puppet 2.6.4
```
Finished in 22.1 seconds (files took 1.69 seconds to load)
905 examples, 8 failures

Failed examples:

rspec ./spec/classes/init_spec.rb:16 # glassfish on a RedHat OSFamily with default param values should compile into a catalogue without dependency cycles
rspec ./spec/classes/install_spec.rb:20 # glassfish::install on a RedHat OSFamily with default param values it should manage user and group should contain User[glassfish] that comes before Exec[change-ownership]
rspec ./spec/classes/install_spec.rb:166 # glassfish::install on a RedHat OSFamily with a custom username and password it should manage user and group should contain User[gftest] that comes before Exec[change-ownership]
rspec ./spec/defines/create_instance_spec.rb:43 # glassfish::create_instance with default params should contain Glassfish::Create_service[test] that requires Cluster_instance[test]
rspec ./spec/defines/create_instance_spec.rb:107 # glassfish::create_instance with a das_host provided should contain Glassfish::Create_service[test] that requires Cluster_instance[test]
rspec ./spec/defines/create_instance_spec.rb:140 # glassfish::create_instance with a service_name specificed should contain Glassfish::Create_service[test] that requires Cluster_instance[test]
rspec ./spec/defines/install_jars_spec.rb:39 # glassfish::install_jars with default params should contain File[/usr/local/glassfish-3.1.2.2/glassfish/lib/ext/test.jar] that requires File[/usr/local/glassfish-3.1.2.2/glassfish/lib/ext]
rspec ./spec/defines/install_jars_spec.rb:105 # glassfish::install_jars with download = true should contain File[/usr/local/glassfish-3.1.2.2/glassfish/lib/ext] that comes before Exec[download_test.jar]


Total resources:   67
Touched resources: 45
Resource coverage: 67.16%
Untouched resources:

  Class[Glassfish::Install]
  Class[Glassfish::Java]
  Class[Glassfish::Params]
  Class[Glassfish::Path]
  Domain[gf_test]
  Domain[gftest]
  Exec[stop_gf_test]
  Exec[stop_gftest]
  File[/usr/local]
  File[gf_test_servicefile]
  File[gftest_asadmin_passfile]
  File[gftest_servicefile]
  Glassfish::Create_asadmin_passfile[gftest_asadmin_passfile]
  Glassfish::Create_domain[gf_test]
  Glassfish::Create_domain[gftest]
  Glassfish::Create_service[gf_test]
  Glassfish::Create_service[gftest]
  Package[unzip]
  Service[gf_service]
  Service[gftest_service]
  Service[glassfish]
  Service[glassfish_instance]
/Users/gavinw/.rvm/rubies/ruby-1.9.3-p551/bin/ruby -I/Users/gavinw/.rvm/gems/ruby-1.9.3-p551@glassfish/gems/rspec-core-3.6.0/lib:/Users/gavinw/.rvm/gems/ruby-1.9.3-p551@glassfish/gems/rspec-support-3.6.0/lib /Users/gavinw/.rvm/gems/ruby-1.9.3-p551@glassfish/gems/rspec-core-3.6.0/exe/rspec --pattern spec/\{aliases,classes,defines,unit,functions,hosts,integration,type_aliases,types\}/\*\*/\*_spec.rb --color failed
bundle exec rake test  26.01s user 2.61s system 43% cpu 1:06.41 total
```

- Rspec-puppet 2.6.5
```

Finished in 2 minutes 0 seconds (files took 1.08 seconds to load)
905 examples, 8 failures

Failed examples:

rspec ./spec/classes/init_spec.rb:16 # glassfish on a RedHat OSFamily with default param values should compile into a catalogue without dependency cycles
rspec ./spec/classes/install_spec.rb:20 # glassfish::install on a RedHat OSFamily with default param values it should manage user and group should contain User[glassfish] that comes before Exec[change-ownership]
rspec ./spec/classes/install_spec.rb:166 # glassfish::install on a RedHat OSFamily with a custom username and password it should manage user and group should contain User[gftest] that comes before Exec[change-ownership]
rspec ./spec/defines/create_instance_spec.rb:43 # glassfish::create_instance with default params should contain Glassfish::Create_service[test] that requires Cluster_instance[test]
rspec ./spec/defines/create_instance_spec.rb:107 # glassfish::create_instance with a das_host provided should contain Glassfish::Create_service[test] that requires Cluster_instance[test]
rspec ./spec/defines/create_instance_spec.rb:140 # glassfish::create_instance with a service_name specificed should contain Glassfish::Create_service[test] that requires Cluster_instance[test]
rspec ./spec/defines/install_jars_spec.rb:39 # glassfish::install_jars with default params should contain File[/usr/local/glassfish-3.1.2.2/glassfish/lib/ext/test.jar] that requires File[/usr/local/glassfish-3.1.2.2/glassfish/lib/ext]
rspec ./spec/defines/install_jars_spec.rb:105 # glassfish::install_jars with download = true should contain File[/usr/local/glassfish-3.1.2.2/glassfish/lib/ext] that comes before Exec[download_test.jar]


Total resources:   67
Touched resources: 45
Resource coverage: 67.16%
Untouched resources:

  Class[Glassfish::Install]
  Class[Glassfish::Java]
  Class[Glassfish::Params]
  Class[Glassfish::Path]
  Domain[gf_test]
  Domain[gftest]
  Exec[stop_gf_test]
  Exec[stop_gftest]
  File[/usr/local]
  File[gf_test_servicefile]
  File[gftest_asadmin_passfile]
  File[gftest_servicefile]
  Glassfish::Create_asadmin_passfile[gftest_asadmin_passfile]
  Glassfish::Create_domain[gf_test]
  Glassfish::Create_domain[gftest]
  Glassfish::Create_service[gf_test]
  Glassfish::Create_service[gftest]
  Package[unzip]
  Service[gf_service]
  Service[gftest_service]
  Service[glassfish]
  Service[glassfish_instance]
/Users/gavinw/.rvm/rubies/ruby-1.9.3-p551/bin/ruby -I/Users/gavinw/.rvm/gems/ruby-1.9.3-p551@glassfish/gems/rspec-core-3.6.0/lib:/Users/gavinw/.rvm/gems/ruby-1.9.3-p551@glassfish/gems/rspec-support-3.6.0/lib /Users/gavinw/.rvm/gems/ruby-1.9.3-p551@glassfish/gems/rspec-core-3.6.0/exe/rspec --pattern spec/\{aliases,classes,defines,unit,functions,hosts,integration,type_aliases,types\}/\*\*/\*_spec.rb --color failed
bundle exec rake test  109.71s user 9.12s system 95% cpu 2:04.30 total
```

**Comment by fatmcgav** [comment]
@rodjek I'm struggling to get `ruby-prof` or `rspec-prof` to run in combination with `bundle exec`. 
I keep getting 'cannot load such file -- rpsec'.

Any pointers?

**Comment by DavidS** [comment]
`rpsec` looks like a type

**Comment by fatmcgav** [comment]
@DavidS - That's what I get for manually typing error messages... ;) 

```
be ruby-prof rspec
Measure Mode: wall_time
Thread ID: 70180919259600
Fiber ID: 70180923257500
Total: 0.000131
Sort by: self_time

 %self      total      self      wait     child     calls  name
 67.82      0.000     0.000     0.000     0.000        1   Class#new
 13.82      0.000     0.000     0.000     0.000        1   <Class::BasicObject>#allocate
 11.45      0.000     0.000     0.000     0.000        1   Global#[No method]
  3.09      0.000     0.000     0.000     0.000        1   Exception#initialize
  1.64      0.000     0.000     0.000     0.000        1   Exception#set_backtrace
  1.45      0.000     0.000     0.000     0.000        2   Exception#exception
  0.73      0.000     0.000     0.000     0.000        2   Exception#backtrace

* indicates recursively called methods
/Users/gavinw/.rvm/gems/ruby-1.9.3-p551@prssvc/gems/ruby-prof-0.16.2/lib/ruby-prof/compatibility.rb:104:in `load': cannot load such file -- rspec (LoadError)
        from /Users/gavinw/.rvm/gems/ruby-1.9.3-p551@prssvc/gems/ruby-prof-0.16.2/lib/ruby-prof/compatibility.rb:104:in `start_script'
        from /Users/gavinw/.rvm/gems/ruby-1.9.3-p551@prssvc/gems/ruby-prof-0.16.2/bin/ruby-prof:292:in `run'
        from /Users/gavinw/.rvm/gems/ruby-1.9.3-p551@prssvc/gems/ruby-prof-0.16.2/bin/ruby-prof:340:in `<top (required)>'
        from /Users/gavinw/.rvm/gems/ruby-1.9.3-p551@prssvc/bin/ruby-prof:22:in `load'
        from /Users/gavinw/.rvm/gems/ruby-1.9.3-p551@prssvc/bin/ruby-prof:22:in `<main>'
        from /Users/gavinw/.rvm/gems/ruby-1.9.3-p551@prssvc/bin/ruby_executable_hooks:15:in `eval'
        from /Users/gavinw/.rvm/gems/ruby-1.9.3-p551@prssvc/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by fatmcgav** [comment]
@rodjek / @DavidS OK, looks like I just had to be a bit more patient with `rspec-prof`, as it was just taking what felt like an inordinately large amount of time to write out the HTML... 

So I've now got 2 html files, one for 2.6.4 and one for 2.6.5... DId you want me to gist them or email?

**Comment by DavidS** [comment]
Probably the easiest is to mail it to pdk-maintainers@puppet.com .

**Comment by fatmcgav** [comment]
@DavidS Cool, ok... Will zip and send over now :)

**Comment by rodjek** [comment]
Thanks @fatmcgav, those ruby-prof results were very useful!

This appears to be an issue that only affects Puppet < 4 which is why I never noticed it during testing. If you give [this branch](https://github.com/rodjek/rspec-puppet/pull/596) a go, it should bring the performance back up.

**Comment by fatmcgav** [comment]
@rodjek I've left a comment on the PR, but it works :)

**Comment by rodjek** [comment]
2.6.8 has been pushed to rubygems with the fix
