### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by TraGicCode** [rodjek/rspec-puppet#645]
If you grab the latest version of the release gem from rubygems and try and run rspec-puppet on a non-windows machine i sometimes get the following error thrown where facter is actuallying trying to execute code and load windows ruby libraries

```
 18) role::windowsupdateserver should compile into a catalogue without dependency cycles
      Failure/Error: it { is_expected.to compile.with_all_deps }

      LoadError:
        cannot load such file -- win32ole
      # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/monkey_patches.rb:282:in `require'
      # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/monkey_patches.rb:282:in `require'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/wmi.rb:18:in `connect'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/wmi.rb:31:in `execquery'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/ip/windows.rb:100:in `network_adapter_configurations'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/ip/windows.rb:140:in `get_preferred_network_adapters'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/ip/windows.rb:115:in `get_preferred_ipv4_adapters'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/ipaddress.rb:110:in `block (2 levels) in <top (required)>'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/resolution.rb:157:in `resolve_value'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/core/resolvable.rb:63:in `block (2 levels) in value'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/core/resolvable.rb:62:in `block in value'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/core/resolvable.rb:84:in `with_timing'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/core/resolvable.rb:61:in `value'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/fact.rb:161:in `block in find_first_real_value'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/fact.rb:160:in `each'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/fact.rb:160:in `find_first_real_value'
```

What i noticed is that if i get the latest version of master this error goes away and my issue gets resolved.  Can someone please cut a new release of this gem?

/cc @rodjek @DavidS

**Comment by rodjek** [comment]
There are a couple of issues that came up when running master against existing community modules (which is part of my pre-release acceptance testing). Once they've been resolved I'll be pushing a 2.6.10 release.
