### ISSUE TITLE
puppetlabs-acl: Unable to test on a non-windows machine

### ISSUE THREAD

**Issue by TraGicCode** [rodjek/rspec-puppet#665]
Looks like there is another issue on another windows module in which windows ruby code is attempting to execute on a non-windows box when running under rspec-puppet.  

## Setup
**rspec-puppet version: 2.6.11**
**Module Version: puppetlabs-acl 2.1.0**
**Operating System: Anything but windows**

## Puppet Code under test
```puppet
acl { 'L:\\SQLBackup':
      inherit_parent_permissions => false,
      permissions                => [
        { 'identity' => $mssql_service_account_user, 'rights' => ['read'] }
      ],
      require                    => Dsc_sqlsetup['Install SQL Server'],
    }
```

## Spec Test
The spec test is just a does it compile test

## Error Message
```
     NoMethodError:
       undefined method `symlink?' for Puppet::Util::Windows::File:Module
     # ./spec/fixtures/modules/acl/lib/puppet/provider/acl/windows.rb:58:in `validate'
     # ./spec/fixtures/modules/acl/lib/puppet/type/acl.rb:376:in `block (2 levels) in <top (required)>'
     # ./.bundle/ruby/2.5.0/gems/puppet-5.3.2/lib/puppet/type.rb:2398:in `initialize'
     # ./spec/fixtures/modules/acl/lib/puppet/type/acl.rb:115:in `initialize'
     # ./.bundle/ruby/2.5.0/gems/puppet-5.3.2/lib/puppet/resource.rb:460:in `new'
     # ./.bundle/ruby/2.5.0/gems/puppet-5.3.2/lib/puppet/resource.rb:460:in `to_ral'
     # ./.bundle/ruby/2.5.0/gems/puppet-5.3.2/lib/puppet/resource/catalog.rb:625:in `block in to_catalog'
     # ./.bundle/ruby/2.5.0/gems/puppet-5.3.2/lib/puppet/resource/catalog.rb:617:in `each'
     # ./.bundle/ruby/2.5.0/gems/puppet-5.3.2/lib/puppet/resource/catalog.rb:617:in `to_catalog'
     # ./.bundle/ruby/2.5.0/gems/puppet-5.3.2/lib/puppet/resource/catalog.rb:498:in `to_ral'
     # ./.bundle/ruby/2.5.0/gems/rspec-puppet-2.6.11/lib/rspec-puppet/matchers/compile.rb:142:in `cycles_found?'
     # ./.bundle/ruby/2.5.0/gems/rspec-puppet-2.6.11/lib/rspec-puppet/matchers/compile.rb:25:in `matches?'
     # ./spec/classes/role/sqlserver_spec.rb:55:in `block (5 levels) in <top (required)>'
```

/cc @mattzajork

**Comment by TraGicCode** [comment]
Here is a link to where this is actually happening at.

https://github.com/puppetlabs/puppetlabs-acl/blob/c1c13ab57630722ac358322cfd766c371c1bd4fe/lib/puppet/provider/acl/windows.rb#L53-L61

**Comment by rodjek** [comment]
@TraGicCode I'm not sure yet how best to handle this sort of situation, I don't really want to end up with rspec-puppet stubbing out every Puppet internal method that is specific to Windows...

In the meantime, you can work around this by stubbing out the call to the provider's `validate` method in your spec tests.

Here's an example using `rspec-mocks`
```
require 'spec_helper'

describe 'foo' do
  on_supported_os.each do |os, os_facts|
    context "on #{os}" do
      let(:facts) { os_facts }

      before(:each) do
        allow_any_instance_of(Puppet::Type.type(:acl).provider(:windows)).to receive(:validate)
      end

      it { is_expected.to compile }
      it { is_expected.to contain_acl('L:\\SQLBackup') }
    end
  end
end
```

**Comment by jadestorm** [comment]
@rodjek First off I apologize for reopening this if my comment does reopen it -- but I was wondering if you happen to know what the modern equivalent of your allow_any_instance_of solution is?  If I try to do that now, I get:

`undefined method `allow_any_instance_of'`

Not having any luck with my google fu I'm afraid.  =(   Thanks!!

**Comment by jadestorm** [comment]
Disregard my question -- for anyone else who comes across this though, the issue turned out to be that I needed to explicitly specify that I needed rspec vs mocha for mock:

https://github.com/puppetlabs/puppetlabs_spec_helper#mock_with

**Comment by krische** [comment]
If I try the `allow_any_instance_of(Puppet::Type.type(:acl).provider(:windows)).to receive(:validate)` trick above, I receive the following error:

```
     Failure/Error: Puppet::Util::Windows::SID.valid_sid?(string_sid)

     NameError:
       uninitialized constant Puppet::Util::Windows::Error
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/util/windows/sid.rb:206:in `rescue in valid_sid?'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/util/windows/sid.rb:204:in `valid_sid?'
     # ./spec/fixtures/modules/acl/lib/puppet/provider/acl/windows/base.rb:135:in `valid_sid?'
     # ./spec/fixtures/modules/acl/lib/puppet/provider/acl/windows/base.rb:529:in `get_account_id'
     # ./spec/fixtures/modules/acl/lib/puppet/provider/acl/windows/base.rb:541:in `get_account_name'
     # ./spec/fixtures/modules/acl/lib/puppet/type/acl.rb:408:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/type.rb:2186:in `instance_eval'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/type.rb:2186:in `block in autorelation'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/type.rb:2125:in `block in eachautorequire'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/type.rb:2124:in `each'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/type.rb:2124:in `eachautorequire'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/type.rb:2181:in `autorelation'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/type.rb:2212:in `autorequire'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/graph/relationship_graph.rb:173:in `block (2 levels) in build_autorelation_dependencies'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/graph/relationship_graph.rb:172:in `each'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/graph/relationship_graph.rb:172:in `block in build_autorelation_dependencies'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/graph/relationship_graph.rb:171:in `each'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/graph/relationship_graph.rb:171:in `build_autorelation_dependencies'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/graph/relationship_graph.rb:25:in `populate_from'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/resource/catalog.rb:266:in `relationship_graph'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-puppet-2.7.8/lib/rspec-puppet/matchers/compile.rb:149:in `cycles_found?'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-puppet-2.7.8/lib/rspec-puppet/matchers/compile.rb:25:in `matches?'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `from_string_to_wide_string' for FFI::MemoryPointer:Class
     #   ./vendor/bundle/ruby/2.5.0/gems/puppet-6.12.0/lib/puppet/util/windows/sid.rb:182:in `string_to_sid_ptr'
```
Are there some more things that need to be mocked?

**Comment by rodjek** [comment]
@krische it looks like in your case you're hitting https://github.com/puppetlabs/puppetlabs-acl/blob/ef4790545602d7356d939d54a004ee4510016069/lib/puppet/type/acl.rb#L408 where the type is calling out to the provider to resolve the `owner` property into a user name using Win32 calls.

If your testing doesn't require this autorequire, you could disable it with something like
```ruby
allow_any_instance_of(Puppet::Type.type(:acl).provider(:windows)).to receive(:respond_to?).with(:get_account_name).and_return(false)
```
Alternatively you can mock the response(s) from this method with something like
```ruby
allow_any_instance_of(Puppet::Type.type(:acl).provider(:windows)).to receive(:get_account_name).with('your owner value').and_return('the expected username')
```
