### ISSUE TITLE
Issue with 'should' in insync function in custom type

### ISSUE THREAD

**Issue by soxwellfb** [rodjek/rspec-puppet#749]
I'm writing a custom type and rspec tests for it, and I'm having trouble testing a custom insync? in a parameter declaration - it looks like the `should` is being mocked with an RSpec Matcher somehow.

I've cut it down as much as possible:

test_type.rb
```
Puppet::Type.newtype(:test_type) do

  desc 'Test Type'

  ensurable do
    defaultvalues
    defaultto :present
  end

  newparam(:name, :namevar => true) do
    desc 'Test name'

    munge do |value|
      value.downcase
    end

    def insync?(is)
      is.downcase == should.downcase
    end
  end
end
```

test_type_spec.rb
```
require 'puppet'

describe Puppet::Type.type(:test_type) do

  let(:resource_name) { 'test' }

  describe 'name' do
    let(:resource) do
      described_class.new(
        :name => resource_name
      )
    end

    let(:name) { resource.parameter(:name) }
    
    describe 'insync?' do
      it 'is test' do
        expect(name.insync?('test')).to be_truthy
      end
    end
  end
end
```

and the rspec output:

```
Puppet::Type::Test_type
  name
    insync?
      is test (FAILED - 1)

Failures:

  1) Puppet::Type::Test_type name insync? is test
     Failure/Error: is.downcase == should.downcase

     NoMethodError:
       undefined method `downcase' for #<RSpec::Matchers::BuiltIn::PositiveOperatorMatcher:0x00000002b067b8>
     # ./lib/puppet/type/test_type.rb:18:in `insync?'
     # ./spec/unit/type/test_type_spec.rb:18:in `block (4 levels) in <top (required)>'

Deprecation Warnings:

Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /etc/puppet/environments/soxwell/modules/privacyidea/lib/puppet/type/test_type.rb:18:in `insync?'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

1 deprecation warning total

Finished in 0.00908 seconds (files took 2.85 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/unit/type/test_type_spec.rb:17 # Puppet::Type::Test_type name insync? is test
```

What am I doing wrong here? Using rspec-puppet 2.7.3, rspec-core 3.8.0 and rspec-expectations 3.8.2.

**Comment by soxwellfb** [comment]
The reason is that `should` is undefined for a parameter, isn't it? That's the bit that's wrong. A parameter can't be out of sync?

**Comment by rodjek** [comment]
This isn't related to rspec-puppet, but rather rspec itself. You're correct that `should` should be undefined for a parameter as there is no state for a parameter to sync, but the old rspec "should" syntax is enabled by default even if it isn't being used which is why you're seeing it as an rspec matcher. I'd recommend disabling the old should syntax by following the directions [here](https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/syntax-configuration#disable-should-syntax)
