### ISSUE TITLE
`facts` is not available on an example group

### ISSUE THREAD

**Issue by threepistons** [rodjek/rspec-puppet#774]
Given: `PDK 1.14.0` and
```
~/git/PUPPET/puppet5(50-rolesprofiles*) » gem list                                                           nhg45@17dcompd454

*** LOCAL GEMS ***

addressable (2.7.0, 2.6.0)
ast (2.4.0)
bigdecimal (1.4.4, default: 1.3.4)
bundler (2.0.2, 2.0.1)
charlock_holmes (0.7.6)
cmath (default: 1.0.0)
colorize (0.8.1)
concurrent-ruby (1.1.5)
crass (1.0.5)
csv (3.1.2, default: 1.0.0)
date (2.0.0, default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.3.1, 1.2.0)
diff-lcs (1.3)
etc (1.0.1, default: 1.0.0)
eventmachine (1.2.7, 1.0.7)
facter (2.5.6, 2.5.1)
facterdb (1.0.0)
fast_gettext (2.0.1, 1.1.2)
fcntl (default: 1.0.0)
ffi (1.11.1, 1.9.25)
fiddle (default: 1.0.0)
fileutils (1.3.0, default: 1.0.2)
gdbm (default: 2.0.0)
gemojione (4.3.2, 3.3.0)
generate-puppetfile (1.0.0)
github-markup (3.0.4, 1.7.0)
gitlab-grit (2.8.2)
gnuplot (2.6.2)
gollum (4.1.4)
gollum-grit_adapter (2.0.0, 1.0.1)
gollum-lib (4.2.10)
gpgme (2.0.19, 2.0.18)
hiera (3.6.0, 3.5.0)
hiera-eyaml (3.0.0)
hiera-eyaml-gpg (0.7.4, 0.6)
highline (2.0.3, 1.6.21)
hocon (1.3.0, 1.2.5)
httpclient (2.8.3)
io-console (0.4.8, default: 0.4.6)
ipaddr (1.2.2, default: 1.2.0)
jaro_winkler (1.5.4, 1.5.2)
jgrep (1.5.1)
json (2.2.0, default: 2.1.0)
json-schema (2.8.1)
kramdown (2.1.0, 1.9.0)
libxml-ruby (2.9.0)
locale (2.1.2)
metaclass (0.0.4)
metadata-json-lint (2.2.0)
mime-types (3.3, 3.2.2)
mime-types-data (3.2019.1009, 3.2018.0812)
mini_portile2 (2.4.0)
minitest (5.13.0, 5.10.3)
mocha (1.9.0, 1.8.0)
multi_json (1.14.1, 1.13.1)
mustache (1.1.0, 0.99.8)
mustermann (1.0.3)
mysql2 (0.4.10)
net-telnet (0.2.0, 0.1.1)
nokogiri (1.10.5, 1.10.1)
nokogumbo (2.0.1)
openssl (2.1.2, default: 2.1.1)
optimist (3.0.0)
paint (2.1.1, 0.8.6)
parallel (1.18.0, 1.13.0)
parser (2.6.5.0, 2.6.0.0)
pathspec (0.2.1)
posix-spawn (0.3.13)
power_assert (1.1.5, 0.2.7)
powerpack (0.1.2)
psych (3.1.0, default: 3.0.2)
public_suffix (4.0.1, 3.0.3)
puppet (6.10.1, 6.2.0, 6.1.0)
puppet-lint (2.4.2, 2.3.3)
puppet-resource_api (1.8.7, 1.6.2)
puppet-syntax (2.6.0, 2.4.3)
puppetlabs_spec_helper (2.14.1, 2.12.0)
rack (2.0.7, 1.6.11)
rack-protection (2.0.7, 1.5.5)
rainbow (3.0.0)
rake (13.0.0, 12.3.2, 12.3.1)
rdoc (6.2.0, default: 6.0.1)
rouge (3.12.0, 2.2.1)
rspec (3.9.0, 3.8.0)
rspec-core (3.9.0, 3.8.0, 3.7.1)
rspec-expectations (3.9.0, 3.8.2, 3.7.0)
rspec-mocks (3.9.0, 3.8.0, 3.7.0)
rspec-puppet (2.7.8, 2.7.2)
rspec-puppet-facts (1.9.6, 1.9.2)
rspec-support (3.9.0, 3.8.0, 3.7.1)
rubocop (0.76.0, 0.63.0)
rubocop-rspec (1.36.0, 1.31.0)
ruby-progressbar (1.10.1, 1.10.0)
sanitize (5.1.0, 2.1.1)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
semantic_puppet (1.0.2)
sinatra (2.0.7, 1.4.8)
spdx-licenses (1.2.0)
sqlite3 (1.4.1, 1.3.13)
stringex (2.8.5)
stringio (0.0.2, default: 0.0.1)
strscan (1.0.3, default: 1.0.0)
svn2git (2.4.0)
test-unit (3.3.4, 3.2.5)
thread_order (1.1.1, 1.1.0)
tilt (2.0.10, 2.0.9)
trollop (2.9.9, 2.0)
twitter-text (1.14.7)
unf (0.1.4)
unf_ext (0.0.7.6, 0.0.7.5)
unicode-display_width (1.6.0, 1.4.1)
useragent (0.16.10)
webrick (1.5.0, default: 1.4.2)
zlib (default: 1.0.0)
```
and a packagemanager_spec.rb file
```Ruby
require 'spec_helper'

describe 'profiles::packagemanager' do
  on_supported_os.each do |os, os_facts|
    let(:facts) do
      os_facts
    end

    context "on #{os}" do
      case facts[:operatingsystem]
      when 'Debian'
        it { is_expected.to compile }
        it { is_expected.to contain_class('apt').with('purge' => { 'sources.list' => true }) }
        it { is_expected.to contain_apt__source('puppetlabs') }
        it { is_expected.to contain_apt__source('ubuntu') }
        it { is_expected.to contain_apt__source('ubuntu-updates') }
        it { is_expected.to contain_apt__source('ubuntu-partner') }
        it { is_expected.to contain_apt__source('ubuntu-security') }
        it { is_expected.to contain_apt__source('telred') }
        it { is_expected.to contain_apt__key('puppetlabs') }
        it { is_expected.to contain_apt__key('ubuntu-archive') }
        it { is_expected.to contain_apt__key('ubuntu-cdimage') }
        it { is_expected.to contain_apt__key('telred') }
      end
    end
  end
end
```
When I run `cd site/profiles ; pdk test unit` in order to test my profiles classes (which are manifests in a module called "profiles" for the purposes of PDK).
I get:
```
pdk (INFO): Using Ruby 2.5.7
pdk (INFO): Using Puppet 6.10.0
[✔] Preparing to run the unit tests.
/opt/puppetlabs/pdk/private/ruby/2.5.7/bin/ruby -I/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rspec-core-3.9.0/lib:/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rspec-support-3.9.0/lib /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rspec-core-3.9.0/exe/rspec --pattern spec/\{aliases,classes,defines,functions,hosts,integration,plans,tasks,type_aliases,types,unit\}/\*\*/\*_spec.rb

An error occurred while loading ./spec/classes/packagemanager_spec.rb.
Failure/Error: case facts[:operatingsystem]
  `facts` is not available on an example group (e.g. a `describe` or `context` block). It is only available from within individual examples (e.g. `it` blocks) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc).
# ./spec/classes/packagemanager_spec.rb:10:in `block (3 levels) in <top (required)>'
# ./spec/classes/packagemanager_spec.rb:9:in `block (2 levels) in <top (required)>'
# ./spec/classes/packagemanager_spec.rb:4:in `each'
# ./spec/classes/packagemanager_spec.rb:4:in `block in <top (required)>'
# ./spec/classes/packagemanager_spec.rb:3:in `<top (required)>'
Run options: exclude {:bolt=>true}

Finished in 0.00003 seconds (files took 26.66 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

/opt/puppetlabs/pdk/private/ruby/2.5.7/bin/ruby -I/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rspec-core-3.9.0/lib:/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rspec-support-3.9.0/lib /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rspec-core-3.9.0/exe/rspec --pattern spec/\{aliases,classes,defines,functions,hosts,integration,plans,tasks,type_aliases,types,unit\}/\*\*/\*_spec.rb failed
```
I expected to be allowed to use facts as outlined at https://rnelson0.com/2016/11/04/puppet-tech-debt-day-3-excluding-os-testing/

Replacing the case block with an if tree gives the same error.

**Comment by threepistons** [comment]
This is user error on my part.

Working syntax as at 5th November 2019:
```Ruby
require 'spec_helper'

describe 'profiles::packagemanager' do
  on_supported_os.each do |os, os_facts|
    let(:facts) do
      os_facts
    end

    context "on #{os}" do
      case os_facts[:operatingsystem]
      when 'Ubuntu'
  [your tests here]
```

Note: `case os_facts[:operatingsystem]` not `case facts[:operatingsystem]`.

Hope this helps someone else.
